export enum ConfigKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  API_KEY = 'API_KEY',
  PRIVATE_KEY = 'PRIVATE_KEY',
  FE_URL = 'FE_URL',
  IS_MAINNET = 'IS_MAINNET',
}
